# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-25 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190325_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=64, verbose_name='姓名'),
        ),
    ]
